services:

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
    networks:
      - db-network

  back:
    build: ./
    container_name: my-node-app
    working_dir: /back
    ports:
      - "3000:3000"
    volumes:
      - ./:/back
    environment:
      DB_HOST: db
      DB_USER: db_user
      DB_PASSWORD: db_password
      DB_NAME: db_name
    depends_on:
      - db
    networks:
      - db-network
    restart: on-failure

networks:
  db-network: